@LightManager.Server_HostAddress = https://localhost:7233

###
POST {{LightManager.Server_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "1@test.se",
  "password": "Abc_1234!"
}
###
